# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives

social:
  email: wangzhelee@gmail.com
  twitter:
  weibo:
  github: https://github.com/Naetw
  googleplus:
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: naetw-github-io #disqus _shortname
google_analytics: #Google Analytics Tracking Code
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code
